services:
    minecraft:
        container_name: xenous-mc

        image: itzg/minecraft-server
        tty: true
        stdin_open: true

        restart: unless-stopped

        ports:
            # Game port
            - 127.0.0.1:25565:25565/tcp
            # Voice chat port
            - 127.0.0.1:24454:24454/udp

        env_file:
            - path: ./.env
              required: true

        environment:
            EULA: true

            # This will allow users to connect and not check for players against Minecraft's account database
            ONLINE_MODE: false
            TYPE: FABRIC

            VERSION: 1.20.1
            DIFFICULTY: normal
            MODE: survival
            LEVEL_TYPE: minecraft:normal # minecraft:normal | minecraft:flat | minecraft:large_biomes 

            MAX_PLAYERS: 5
            VIEW_DISTANCE: 8
            MEMORY: 4G

            SERVER_NAME: Xenous
            MOTD: Xenous Minecraft Server
            ICON: https://github.com/Xenous-Inc/minecraft/blob/main/logo.png?raw=true
            OVERRIDE_ICON: true

            CF_API_KEY: ${CF_API_KEY}

        volumes:
            # attach the relative directory 'data' to the container's /data path
            - ./data:/data
